-- Script completo de marcas y modelos de autos del mercado argentino
-- PARTE 1: Marcas A-C

DELETE FROM models;
DELETE FROM makes;

-- ALFA ROMEO
INSERT IGNORE INTO makes (name) VALUES ('Alfa Romeo');
INSERT IGNORE INTO models (make_id, name)
SELECT m.id, '147' FROM makes m WHERE m.name = 'Alfa Romeo'
UNION ALL SELECT m.id, '156' FROM makes m WHERE m.name = 'Alfa Romeo'
UNION ALL SELECT m.id, '159' FROM makes m WHERE m.name = 'Alfa Romeo'
UNION ALL SELECT m.id, '166' FROM makes m WHERE m.name = 'Alfa Romeo'
UNION ALL SELECT m.id, 'Brera' FROM makes m WHERE m.name = 'Alfa Romeo'
UNION ALL SELECT m.id, 'Giulietta' FROM makes m WHERE m.name = 'Alfa Romeo'
UNION ALL SELECT m.id, 'Giulia' FROM makes m WHERE m.name = 'Alfa Romeo'
UNION ALL SELECT m.id, 'Stelvio' FROM makes m WHERE m.name = 'Alfa Romeo'
UNION ALL SELECT m.id, 'Tonale' FROM makes m WHERE m.name = 'Alfa Romeo';

-- AUDI
-- AUDI con modelos específicos
INSERT IGNORE INTO makes (name) VALUES ('Audi');
INSERT IGNORE INTO models (make_id, name)
SELECT m.id, 'A1 1.4 TFSI' FROM makes m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'A1 1.0 TFSI' FROM makes m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'A3 1.4 TFSI' FROM makes m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'A3 2.0 TFSI' FROM makes m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'A3 1.6 TDI' FROM makes m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'A3 2.0 TDI' FROM makes m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'A4 1.4 TFSI' FROM makes m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'A4 2.0 TFSI' FROM makes m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'A4 2.0 TDI' FROM makes m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'A5 2.0 TFSI' FROM makes m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'A5 2.0 TDI' FROM makes m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'A6 2.0 TFSI' FROM makes m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'A6 2.0 TDI' FROM makes m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'A6 3.0 TDI' FROM makes m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'A7 3.0 TFSI' FROM makes m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'A7 3.0 TDI' FROM makes m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'A8 4.0 TFSI' FROM makes m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'A8 3.0 TDI' FROM makes m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'Q2 1.0 TFSI' FROM makes m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'Q2 1.4 TFSI' FROM makes m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'Q3 1.4 TFSI' FROM makes m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'Q3 2.0 TFSI' FROM makes m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'Q3 2.0 TDI' FROM makes m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'Q5 2.0 TFSI' FROM makes m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'Q5 2.0 TDI' FROM makes m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'Q5 3.0 TDI' FROM makes m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'Q7 3.0 TFSI' FROM makes m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'Q7 3.0 TDI' FROM makes m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'Q8 3.0 TFSI' FROM makes m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'Q8 3.0 TDI' FROM makes m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'TT 2.0 TFSI' FROM makes m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'TT RS' FROM makes m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'RS3' FROM makes m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'RS4' FROM makes m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'RS5' FROM makes m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'RS6' FROM makes m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'RS7' FROM makes m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'S3' FROM makes m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'S4' FROM makes m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'S5' FROM makes m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'S6' FROM makes m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'S7' FROM makes m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'S8' FROM makes m WHERE m.name = 'Audi';

-- BMW
-- BMW con modelos específicos
INSERT IGNORE INTO makes (name) VALUES ('BMW');
INSERT IGNORE INTO models (make_id, name)
SELECT m.id, '116i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '118i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '120i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '125i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '130i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '135i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'M135i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'M140i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '218i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '220i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '225i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '228i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '230i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '235i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '240i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'M235i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'M240i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '316i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '318i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '320i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '323i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '325i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '328i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '330i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '335i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '340i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'M3' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'M340i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '420i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '425i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '428i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '430i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '435i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '440i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'M4' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'M440i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '520i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '523i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '525i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '528i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '530i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '535i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '540i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '545i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '550i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'M5' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'M550i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '640i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '650i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'M6' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '730i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '740i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '750i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '760i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'M760i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '840i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '850i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'M8' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'X1 sDrive18i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'X1 xDrive20i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'X1 xDrive25i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'X2 sDrive18i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'X2 xDrive20i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'X2 M35i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'X3 xDrive20i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'X3 xDrive30i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'X3 M40i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'X3 M' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'X4 xDrive20i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'X4 xDrive30i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'X4 M40i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'X4 M' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'X5 xDrive40i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'X5 xDrive50i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'X5 M50i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'X5 M' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'X6 xDrive40i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'X6 xDrive50i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'X6 M50i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'X6 M' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'X7 xDrive40i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'X7 xDrive50i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'X7 M50i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'Z4 sDrive20i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'Z4 sDrive30i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'Z4 M40i' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'i3' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'i4 eDrive40' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'i4 M50' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'i7 xDrive60' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'iX xDrive50' FROM makes m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'iX M60' FROM makes m WHERE m.name = 'BMW';

-- CITROËN
-- CITROËN: Modelos históricos, actuales, variantes y utilitarios en Argentina
INSERT IGNORE INTO makes (name) VALUES ('Citroën');
INSERT IGNORE INTO models (make_id, name)
SELECT m.id, '2CV' FROM makes m WHERE m.name = 'Citroën'
UNION ALL SELECT m.id, '3CV' FROM makes m WHERE m.name = 'Citroën'
UNION ALL SELECT m.id, 'Ami 8' FROM makes m WHERE m.name = 'Citroën'
UNION ALL SELECT m.id, 'Mehari' FROM makes m WHERE m.name = 'Citroën'
UNION ALL SELECT m.id, 'Visa' FROM makes m WHERE m.name = 'Citroën'
UNION ALL SELECT m.id, 'BX' FROM makes m WHERE m.name = 'Citroën'
UNION ALL SELECT m.id, 'ZX' FROM makes m WHERE m.name = 'Citroën'
UNION ALL SELECT m.id, 'Xsara' FROM makes m WHERE m.name = 'Citroën'
UNION ALL SELECT m.id, 'Xsara Picasso' FROM makes m WHERE m.name = 'Citroën'
UNION ALL SELECT m.id, 'C3' FROM makes m WHERE m.name = 'Citroën'
UNION ALL SELECT m.id, 'C3 Aircross' FROM makes m WHERE m.name = 'Citroën'
UNION ALL SELECT m.id, 'C3 Picasso' FROM makes m WHERE m.name = 'Citroën'
UNION ALL SELECT m.id, 'C4' FROM makes m WHERE m.name = 'Citroën'
UNION ALL SELECT m.id, 'C4 Lounge' FROM makes m WHERE m.name = 'Citroën'
UNION ALL SELECT m.id, 'C4 Cactus' FROM makes m WHERE m.name = 'Citroën'
UNION ALL SELECT m.id, 'C4 Picasso' FROM makes m WHERE m.name = 'Citroën'
UNION ALL SELECT m.id, 'C5' FROM makes m WHERE m.name = 'Citroën'
UNION ALL SELECT m.id, 'C5 Aircross' FROM makes m WHERE m.name = 'Citroën'
UNION ALL SELECT m.id, 'Berlingo' FROM makes m WHERE m.name = 'Citroën'
UNION ALL SELECT m.id, 'Berlingo Multispace' FROM makes m WHERE m.name = 'Citroën'
UNION ALL SELECT m.id, 'Berlingo Furgón' FROM makes m WHERE m.name = 'Citroën'
UNION ALL SELECT m.id, 'Jumpy' FROM makes m WHERE m.name = 'Citroën'
UNION ALL SELECT m.id, 'Jumper' FROM makes m WHERE m.name = 'Citroën'
UNION ALL SELECT m.id, 'Nemo' FROM makes m WHERE m.name = 'Citroën'
UNION ALL SELECT m.id, 'C-Elysée' FROM makes m WHERE m.name = 'Citroën'
UNION ALL SELECT m.id, 'C1' FROM makes m WHERE m.name = 'Citroën'
UNION ALL SELECT m.id, 'C2' FROM makes m WHERE m.name = 'Citroën'
UNION ALL SELECT m.id, 'C6' FROM makes m WHERE m.name = 'Citroën'
UNION ALL SELECT m.id, 'DS3' FROM makes m WHERE m.name = 'Citroën'
UNION ALL SELECT m.id, 'DS4' FROM makes m WHERE m.name = 'Citroën'
UNION ALL SELECT m.id, 'DS5' FROM makes m WHERE m.name = 'Citroën'
UNION ALL SELECT m.id, 'C-Zero' FROM makes m WHERE m.name = 'Citroën'
UNION ALL SELECT m.id, 'E-C4' FROM makes m WHERE m.name = 'Citroën'
UNION ALL SELECT m.id, 'E-Berlingo' FROM makes m WHERE m.name = 'Citroën';

-- Script completo de marcas y modelos de autos del mercado argentino
-- PARTE 2: Marcas D-F

-- DACIA
INSERT IGNORE INTO makes (name) VALUES ('Dacia');
INSERT IGNORE INTO models (make_id, name)
SELECT m.id, 'Sandero' FROM makes m WHERE m.name = 'Dacia'
UNION ALL SELECT m.id, 'Logan' FROM makes m WHERE m.name = 'Dacia'
UNION ALL SELECT m.id, 'Duster' FROM makes m WHERE m.name = 'Dacia'
UNION ALL SELECT m.id, 'Spring' FROM makes m WHERE m.name = 'Dacia'
UNION ALL SELECT m.id, 'Jogger' FROM makes m WHERE m.name = 'Dacia'
UNION ALL SELECT m.id, 'Dokker' FROM makes m WHERE m.name = 'Dacia'
UNION ALL SELECT m.id, 'Lodgy' FROM makes m WHERE m.name = 'Dacia'
UNION ALL SELECT m.id, 'Pickup' FROM makes m WHERE m.name = 'Dacia';

-- FIAT
-- FIAT: Modelos históricos, actuales, variantes y utilitarios en Argentina
INSERT IGNORE INTO makes (name) VALUES ('Fiat');
INSERT IGNORE INTO models (make_id, name)
SELECT m.id, '600' FROM makes m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, '800' FROM makes m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, '1100' FROM makes m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, '128' FROM makes m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, '147' FROM makes m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Duna' FROM makes m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Duna Weekend' FROM makes m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Uno' FROM makes m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Uno Fire' FROM makes m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Uno Way' FROM makes m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Spazio' FROM makes m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Regatta' FROM makes m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Siena' FROM makes m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Siena EL' FROM makes m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Siena Fire' FROM makes m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Palio' FROM makes m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Palio Fire' FROM makes m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Palio Adventure' FROM makes m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Palio Weekend' FROM makes m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Palio EL' FROM makes m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Palio HL' FROM makes m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Palio Sporting' FROM makes m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Palio Attractive' FROM makes m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Palio Essence' FROM makes m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Palio 1.3' FROM makes m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Palio 1.4' FROM makes m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Palio 1.6' FROM makes m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Palio 1.8' FROM makes m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Punto' FROM makes m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Punto Attractive' FROM makes m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Punto Essence' FROM makes m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Punto Sporting' FROM makes m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Linea' FROM makes m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Idea' FROM makes m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Idea Adventure' FROM makes m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Mobi' FROM makes m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Mobi Easy' FROM makes m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Mobi Like' FROM makes m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Mobi Way' FROM makes m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Argo' FROM makes m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Argo Drive' FROM makes m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Argo Precision' FROM makes m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Argo Trekking' FROM makes m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Cronos' FROM makes m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Cronos Drive' FROM makes m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Cronos Precision' FROM makes m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Strada' FROM makes m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Strada Working' FROM makes m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Strada Adventure' FROM makes m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Strada Freedom' FROM makes m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Strada Volcano' FROM makes m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Toro' FROM makes m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Toro Freedom' FROM makes m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Toro Volcano' FROM makes m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Toro Ranch' FROM makes m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, '500' FROM makes m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, '500 Lounge' FROM makes m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, '500 Sport' FROM makes m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, '500X' FROM makes m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, '500L' FROM makes m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Fiorino' FROM makes m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Fiorino Furgón' FROM makes m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Ducato' FROM makes m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Ducato Maxi' FROM makes m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Ducato Minibus' FROM makes m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Qubo' FROM makes m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Doblo' FROM makes m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Doblo Adventure' FROM makes m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Palio Weekend Adventure' FROM makes m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Palio Weekend Trekking' FROM makes m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Palio Weekend ELX' FROM makes m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Palio Weekend HL' FROM makes m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Palio Weekend Stile' FROM makes m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Palio Weekend Locker' FROM makes m WHERE m.name = 'Fiat';

-- FORD

-- FORD: Modelos históricos, actuales, variantes y utilitarios en Argentina
INSERT IGNORE INTO makes (name) VALUES ('Ford');
INSERT IGNORE INTO models (make_id, name)
SELECT m.id, 'Falcon' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Taunus' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Sierra' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Escort' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Fiesta' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Fiesta Max' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Fiesta One' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Fiesta KD' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Focus' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Focus II' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Focus III' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Focus Trend' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Focus Titanium' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Ka' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Ka+ (Ka Plus)' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Ka Freestyle' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Mondeo' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Mondeo Vignale' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Mondeo Titanium' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Mondeo Ghia' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Mondeo LX' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Orion' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Fiesta Kinetic' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'EcoSport' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'EcoSport 2da generación' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'EcoSport Freestyle' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'EcoSport Titanium' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Kuga' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Kuga Hybrid' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Territory' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Territory Titanium' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Ranger' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Ranger XL' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Ranger XLS' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Ranger XLT' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Ranger Limited' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Ranger Raptor' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'F-100' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'F-150' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'F-150 Lariat' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'F-150 Raptor' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Courier' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Transit' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Transit Custom' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Transit Connect' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Galaxy' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'S-Max' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'B-Max' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'C-Max' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Escape' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Edge' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Explorer' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Expedition' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Bronco' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Mustang' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Mustang GT' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Mustang Mach 1' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Mustang Mach-E' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Fairlane' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'LTD' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Custom' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Deluxe' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Granada' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Scorpio' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Laser' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Courier Van' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Pampa' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'F-350' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'F-4000' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Super Duty' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Ranger Cabina Simple' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Ranger Cabina Doble' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Ranger Limited Plus' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Ranger Storm' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Ranger Black Edition' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Ranger FX4' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Ranger Wildtrak' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Ranger Thunder' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Ranger Limited 3.2' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Ranger XLS 2.2' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Ranger XLT 3.2' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Ranger XLT 2.2' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Ranger XL 2.2' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Ranger XL 3.2' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Ranger Limited 2.2' FROM makes m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Ranger Limited 3.2' FROM makes m WHERE m.name = 'Ford';
-- CHEVROLET con modelos específicos
-- CHEVROLET: Modelos históricos, actuales, variantes y utilitarios en Argentina
INSERT IGNORE INTO makes (name) VALUES ('Chevrolet');
INSERT IGNORE INTO models (make_id, name)
SELECT m.id, 'Corsa' FROM makes m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Corsa II' FROM makes m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Corsa Classic' FROM makes m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Corsa Wagon' FROM makes m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Celta' FROM makes m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Astra' FROM makes m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Astra GSi' FROM makes m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Vectra' FROM makes m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Vectra GT' FROM makes m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Meriva' FROM makes m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Zafira' FROM makes m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Aveo' FROM makes m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Sonic' FROM makes m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Onix' FROM makes m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Onix Joy' FROM makes m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Onix Plus' FROM makes m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Prisma' FROM makes m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Prisma Joy' FROM makes m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Cruze' FROM makes m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Cruze 5' FROM makes m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Spin' FROM makes m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Spin Activ' FROM makes m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Tracker' FROM makes m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Tracker Turbo' FROM makes m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Captiva' FROM makes m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'S10' FROM makes m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'S10 High Country' FROM makes m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Montana' FROM makes m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Blazer' FROM makes m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Silverado' FROM makes m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Camaro' FROM makes m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Camaro SS' FROM makes m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Corvette' FROM makes m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Malibu' FROM makes m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Impala' FROM makes m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'C-10' FROM makes m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'D-20' FROM makes m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'LUV' FROM makes m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Sprint' FROM makes m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'C-20' FROM makes m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'C-30' FROM makes m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, '400' FROM makes m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Chevy' FROM makes m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Super' FROM makes m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Nova' FROM makes m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Monza' FROM makes m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Opala' FROM makes m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Kadett' FROM makes m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Ipanema' FROM makes m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Corsa Wagon' FROM makes m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Corsa Pick-Up' FROM makes m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Corsa Utility' FROM makes m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Corsa Classic' FROM makes m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Corsa II 1.8' FROM makes m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Corsa II 1.4' FROM makes m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Corsa II 1.6' FROM makes m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Corsa Classic 1.4' FROM makes m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Corsa Classic 1.6' FROM makes m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Corsa Classic 1.7 Diesel' FROM makes m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Corsa Wagon 1.6' FROM makes m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Corsa Wagon 1.4' FROM makes m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Corsa Pick-Up 1.7 Diesel' FROM makes m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Corsa Pick-Up 1.6' FROM makes m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Corsa Utility 1.7 Diesel' FROM makes m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Corsa Utility 1.6' FROM makes m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Corsa Utility 1.4' FROM makes m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Corsa Utility 1.8' FROM makes m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Corsa Utility 1.3' FROM makes m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Corsa Utility 1.2' FROM makes m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Corsa Utility 1.0' FROM makes m WHERE m.name = 'Chevrolet';

-- Script completo de marcas y modelos de autos del mercado argentino
-- PARTE 3: Marcas H-L

-- HONDA
-- HONDA: Modelos históricos, actuales, variantes y SUV en Argentina
INSERT IGNORE INTO makes (name) VALUES ('Honda');
INSERT IGNORE INTO models (make_id, name)
SELECT m.id, 'Civic' FROM makes m WHERE m.name = 'Honda'
UNION ALL SELECT m.id, 'Civic EX' FROM makes m WHERE m.name = 'Honda'
UNION ALL SELECT m.id, 'Civic EXS' FROM makes m WHERE m.name = 'Honda'
UNION ALL SELECT m.id, 'Civic LXS' FROM makes m WHERE m.name = 'Honda'
UNION ALL SELECT m.id, 'Civic SI' FROM makes m WHERE m.name = 'Honda'
UNION ALL SELECT m.id, 'Civic Type R' FROM makes m WHERE m.name = 'Honda'
UNION ALL SELECT m.id, 'City' FROM makes m WHERE m.name = 'Honda'
UNION ALL SELECT m.id, 'City EX' FROM makes m WHERE m.name = 'Honda'
UNION ALL SELECT m.id, 'City EXL' FROM makes m WHERE m.name = 'Honda'
UNION ALL SELECT m.id, 'Fit' FROM makes m WHERE m.name = 'Honda'
UNION ALL SELECT m.id, 'Fit EX' FROM makes m WHERE m.name = 'Honda'
UNION ALL SELECT m.id, 'Fit EXL' FROM makes m WHERE m.name = 'Honda'
UNION ALL SELECT m.id, 'WR-V' FROM makes m WHERE m.name = 'Honda'
UNION ALL SELECT m.id, 'HR-V' FROM makes m WHERE m.name = 'Honda'
UNION ALL SELECT m.id, 'HR-V EX' FROM makes m WHERE m.name = 'Honda'
UNION ALL SELECT m.id, 'HR-V EXL' FROM makes m WHERE m.name = 'Honda'
UNION ALL SELECT m.id, 'CR-V' FROM makes m WHERE m.name = 'Honda'
UNION ALL SELECT m.id, 'CR-V EX' FROM makes m WHERE m.name = 'Honda'
UNION ALL SELECT m.id, 'CR-V EXL' FROM makes m WHERE m.name = 'Honda'
UNION ALL SELECT m.id, 'CR-V Touring' FROM makes m WHERE m.name = 'Honda'
UNION ALL SELECT m.id, 'Pilot' FROM makes m WHERE m.name = 'Honda'
UNION ALL SELECT m.id, 'Odyssey' FROM makes m WHERE m.name = 'Honda'
UNION ALL SELECT m.id, 'Ridgeline' FROM makes m WHERE m.name = 'Honda';

-- HYUNDAI
-- HYUNDAI: Modelos históricos, actuales, variantes y SUV en Argentina
INSERT IGNORE INTO makes (name) VALUES ('Hyundai');
INSERT IGNORE INTO models (make_id, name)
SELECT m.id, 'Accent' FROM makes m WHERE m.name = 'Hyundai'
UNION ALL SELECT m.id, 'Atos' FROM makes m WHERE m.name = 'Hyundai'
UNION ALL SELECT m.id, 'Creta' FROM makes m WHERE m.name = 'Hyundai'
UNION ALL SELECT m.id, 'Elantra' FROM makes m WHERE m.name = 'Hyundai'
UNION ALL SELECT m.id, 'Grand i10' FROM makes m WHERE m.name = 'Hyundai'
UNION ALL SELECT m.id, 'HB20' FROM makes m WHERE m.name = 'Hyundai'
UNION ALL SELECT m.id, 'i10' FROM makes m WHERE m.name = 'Hyundai'
UNION ALL SELECT m.id, 'i20' FROM makes m WHERE m.name = 'Hyundai'
UNION ALL SELECT m.id, 'i30' FROM makes m WHERE m.name = 'Hyundai'
UNION ALL SELECT m.id, 'i35' FROM makes m WHERE m.name = 'Hyundai'
UNION ALL SELECT m.id, 'Kona' FROM makes m WHERE m.name = 'Hyundai'
UNION ALL SELECT m.id, 'Santa Fe' FROM makes m WHERE m.name = 'Hyundai'
UNION ALL SELECT m.id, 'Santa Fe XL' FROM makes m WHERE m.name = 'Hyundai'
UNION ALL SELECT m.id, 'Tucson' FROM makes m WHERE m.name = 'Hyundai'
UNION ALL SELECT m.id, 'Venue' FROM makes m WHERE m.name = 'Hyundai'
UNION ALL SELECT m.id, 'Veloster' FROM makes m WHERE m.name = 'Hyundai'
UNION ALL SELECT m.id, 'Verna' FROM makes m WHERE m.name = 'Hyundai'
UNION ALL SELECT m.id, 'Sonata' FROM makes m WHERE m.name = 'Hyundai'
UNION ALL SELECT m.id, 'Azera' FROM makes m WHERE m.name = 'Hyundai'
UNION ALL SELECT m.id, 'H1' FROM makes m WHERE m.name = 'Hyundai'
UNION ALL SELECT m.id, 'H100' FROM makes m WHERE m.name = 'Hyundai'
UNION ALL SELECT m.id, 'Starex' FROM makes m WHERE m.name = 'Hyundai';
-- JEEP
-- JEEP: Modelos históricos, actuales, variantes y SUV en Argentina
INSERT IGNORE INTO makes (name) VALUES ('Jeep');
INSERT IGNORE INTO models (make_id, name)
SELECT m.id, 'Renegade' FROM makes m WHERE m.name = 'Jeep'
UNION ALL SELECT m.id, 'Compass' FROM makes m WHERE m.name = 'Jeep'
UNION ALL SELECT m.id, 'Commander' FROM makes m WHERE m.name = 'Jeep'
UNION ALL SELECT m.id, 'Cherokee' FROM makes m WHERE m.name = 'Jeep'
UNION ALL SELECT m.id, 'Grand Cherokee' FROM makes m WHERE m.name = 'Jeep'
UNION ALL SELECT m.id, 'Wrangler' FROM makes m WHERE m.name = 'Jeep'
UNION ALL SELECT m.id, 'Gladiator' FROM makes m WHERE m.name = 'Jeep'
UNION ALL SELECT m.id, 'Patriot' FROM makes m WHERE m.name = 'Jeep'
UNION ALL SELECT m.id, 'Liberty' FROM makes m WHERE m.name = 'Jeep'
UNION ALL SELECT m.id, 'Wagoneer' FROM makes m WHERE m.name = 'Jeep'
UNION ALL SELECT m.id, 'CJ-5' FROM makes m WHERE m.name = 'Jeep'
UNION ALL SELECT m.id, 'CJ-7' FROM makes m WHERE m.name = 'Jeep'
UNION ALL SELECT m.id, 'Willys' FROM makes m WHERE m.name = 'Jeep';

-- KIA
-- KIA: Modelos históricos, actuales, variantes y SUV en Argentina
INSERT IGNORE INTO makes (name) VALUES ('Kia');
INSERT IGNORE INTO models (make_id, name)
SELECT m.id, 'Picanto' FROM makes m WHERE m.name = 'Kia'
UNION ALL SELECT m.id, 'Rio' FROM makes m WHERE m.name = 'Kia'
UNION ALL SELECT m.id, 'Cerato' FROM makes m WHERE m.name = 'Kia'
UNION ALL SELECT m.id, 'Soul' FROM makes m WHERE m.name = 'Kia'
UNION ALL SELECT m.id, 'Seltos' FROM makes m WHERE m.name = 'Kia'
UNION ALL SELECT m.id, 'Sportage' FROM makes m WHERE m.name = 'Kia'
UNION ALL SELECT m.id, 'Sorento' FROM makes m WHERE m.name = 'Kia'
UNION ALL SELECT m.id, 'Carnival' FROM makes m WHERE m.name = 'Kia'
UNION ALL SELECT m.id, 'Stinger' FROM makes m WHERE m.name = 'Kia'
UNION ALL SELECT m.id, 'Mohave' FROM makes m WHERE m.name = 'Kia'
UNION ALL SELECT m.id, 'Optima' FROM makes m WHERE m.name = 'Kia'
UNION ALL SELECT m.id, 'Bongo' FROM makes m WHERE m.name = 'Kia'
UNION ALL SELECT m.id, 'K2500' FROM makes m WHERE m.name = 'Kia'
UNION ALL SELECT m.id, 'K2700' FROM makes m WHERE m.name = 'Kia';

-- LAND ROVER
INSERT IGNORE INTO makes (name) VALUES ('Land Rover');
INSERT IGNORE INTO models (make_id, name)
SELECT m.id, 'Defender' FROM makes m WHERE m.name = 'Land Rover'
UNION ALL SELECT m.id, 'Discovery' FROM makes m WHERE m.name = 'Land Rover'
UNION ALL SELECT m.id, 'Discovery Sport' FROM makes m WHERE m.name = 'Land Rover'
UNION ALL SELECT m.id, 'Range Rover' FROM makes m WHERE m.name = 'Land Rover'
UNION ALL SELECT m.id, 'Range Rover Evoque' FROM makes m WHERE m.name = 'Land Rover'
UNION ALL SELECT m.id, 'Range Rover Sport' FROM makes m WHERE m.name = 'Land Rover'
UNION ALL SELECT m.id, 'Range Rover Velar' FROM makes m WHERE m.name = 'Land Rover'
UNION ALL SELECT m.id, 'Freelander' FROM makes m WHERE m.name = 'Land Rover';

-- Script completo de marcas y modelos de autos del mercado argentino
-- PARTE 4: Marcas M-R

-- MERCEDES-BENZ
-- MERCEDES-BENZ con modelos específicos
INSERT IGNORE INTO makes (name) VALUES ('Mercedes-Benz');
INSERT IGNORE INTO models (make_id, name)
SELECT m.id, 'A180' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'A200' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'A250' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'A35 AMG' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'A45 AMG' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'B180' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'B200' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'B250' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'C180' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'C200' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'C250' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'C300' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'C350e' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'C400' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'C43 AMG' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'C63 AMG' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'CLA180' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'CLA200' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'CLA250' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'CLA35 AMG' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'CLA45 AMG' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'CLS350' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'CLS400' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'CLS450' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'CLS53 AMG' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'E200' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'E250' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'E300' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'E350' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'E400' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'E450' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'E43 AMG' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'E53 AMG' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'E63 AMG' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'GLA180' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'GLA200' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'GLA250' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'GLA35 AMG' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'GLA45 AMG' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'GLB200' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'GLB250' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'GLB35 AMG' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'GLC200' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'GLC250' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'GLC300' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'GLC43 AMG' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'GLC63 AMG' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'GLE350' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'GLE400' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'GLE450' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'GLE53 AMG' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'GLE63 AMG' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'GLS450' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'GLS580' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'GLS63 AMG' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'S400' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'S450' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'S500' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'S560' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'S580' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'S63 AMG' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'S65 AMG' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'SL400' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'SL500' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'SL63 AMG' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'SL65 AMG' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'Vito' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'Sprinter' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'Clase X' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'GLA' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'GLB' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'GLC' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'GLE' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'GLS' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'EQB' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'EQA' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'EQC' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'EQS' FROM makes m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'AMG GT' FROM makes m WHERE m.name = 'Mercedes-Benz';
-- NISSAN
-- NISSAN: Modelos históricos, actuales, variantes y SUV en Argentina
INSERT IGNORE INTO makes (name) VALUES ('Nissan');
INSERT IGNORE INTO models (make_id, name)
SELECT m.id, 'March' FROM makes m WHERE m.name = 'Nissan'
UNION ALL SELECT m.id, 'Versa' FROM makes m WHERE m.name = 'Nissan'
UNION ALL SELECT m.id, 'Versa Advance' FROM makes m WHERE m.name = 'Nissan'
UNION ALL SELECT m.id, 'Versa Exclusive' FROM makes m WHERE m.name = 'Nissan'
UNION ALL SELECT m.id, 'Sentra' FROM makes m WHERE m.name = 'Nissan'
UNION ALL SELECT m.id, 'Sentra Advance' FROM makes m WHERE m.name = 'Nissan'
UNION ALL SELECT m.id, 'Sentra Exclusive' FROM makes m WHERE m.name = 'Nissan'
UNION ALL SELECT m.id, 'Tiida' FROM makes m WHERE m.name = 'Nissan'
UNION ALL SELECT m.id, 'Note' FROM makes m WHERE m.name = 'Nissan'
UNION ALL SELECT m.id, 'Altima' FROM makes m WHERE m.name = 'Nissan'
UNION ALL SELECT m.id, '370Z' FROM makes m WHERE m.name = 'Nissan'
UNION ALL SELECT m.id, 'Kicks' FROM makes m WHERE m.name = 'Nissan'
UNION ALL SELECT m.id, 'Kicks Advance' FROM makes m WHERE m.name = 'Nissan'
UNION ALL SELECT m.id, 'Kicks Exclusive' FROM makes m WHERE m.name = 'Nissan'
UNION ALL SELECT m.id, 'Qashqai' FROM makes m WHERE m.name = 'Nissan'
UNION ALL SELECT m.id, 'X-Trail' FROM makes m WHERE m.name = 'Nissan'
UNION ALL SELECT m.id, 'Murano' FROM makes m WHERE m.name = 'Nissan'
UNION ALL SELECT m.id, 'Frontier' FROM makes m WHERE m.name = 'Nissan'
UNION ALL SELECT m.id, 'Frontier XE' FROM makes m WHERE m.name = 'Nissan'
UNION ALL SELECT m.id, 'Frontier LE' FROM makes m WHERE m.name = 'Nissan'
UNION ALL SELECT m.id, 'Frontier Platinum' FROM makes m WHERE m.name = 'Nissan'
UNION ALL SELECT m.id, 'Navara' FROM makes m WHERE m.name = 'Nissan'
UNION ALL SELECT m.id, 'NP300' FROM makes m WHERE m.name = 'Nissan'
UNION ALL SELECT m.id, 'Pathfinder' FROM makes m WHERE m.name = 'Nissan'
UNION ALL SELECT m.id, 'Patrol' FROM makes m WHERE m.name = 'Nissan'
UNION ALL SELECT m.id, 'LEAF' FROM makes m WHERE m.name = 'Nissan';

-- PEUGEOT
-- PEUGEOT: Modelos históricos, actuales, variantes y utilitarios en Argentina
INSERT IGNORE INTO makes (name) VALUES ('Peugeot');
INSERT IGNORE INTO models (make_id, name)
SELECT m.id, '104' FROM makes m WHERE m.name = 'Peugeot'
UNION ALL SELECT m.id, '106' FROM makes m WHERE m.name = 'Peugeot'
UNION ALL SELECT m.id, '205' FROM makes m WHERE m.name = 'Peugeot'
UNION ALL SELECT m.id, '206' FROM makes m WHERE m.name = 'Peugeot'
UNION ALL SELECT m.id, '206 Compact' FROM makes m WHERE m.name = 'Peugeot'
UNION ALL SELECT m.id, '207' FROM makes m WHERE m.name = 'Peugeot'
UNION ALL SELECT m.id, '207 Compact' FROM makes m WHERE m.name = 'Peugeot'
UNION ALL SELECT m.id, '208' FROM makes m WHERE m.name = 'Peugeot'
UNION ALL SELECT m.id, '301' FROM makes m WHERE m.name = 'Peugeot'
UNION ALL SELECT m.id, '304' FROM makes m WHERE m.name = 'Peugeot'
UNION ALL SELECT m.id, '305' FROM makes m WHERE m.name = 'Peugeot'
UNION ALL SELECT m.id, '306' FROM makes m WHERE m.name = 'Peugeot'
UNION ALL SELECT m.id, '307' FROM makes m WHERE m.name = 'Peugeot'
UNION ALL SELECT m.id, '308' FROM makes m WHERE m.name = 'Peugeot'
UNION ALL SELECT m.id, '309' FROM makes m WHERE m.name = 'Peugeot'
UNION ALL SELECT m.id, '405' FROM makes m WHERE m.name = 'Peugeot'
UNION ALL SELECT m.id, '405 SR' FROM makes m WHERE m.name = 'Peugeot'
UNION ALL SELECT m.id, '405 SRI' FROM makes m WHERE m.name = 'Peugeot'
UNION ALL SELECT m.id, '405 GR' FROM makes m WHERE m.name = 'Peugeot'
UNION ALL SELECT m.id, '405 GL' FROM makes m WHERE m.name = 'Peugeot'
UNION ALL SELECT m.id, '405 GTX' FROM makes m WHERE m.name = 'Peugeot'
UNION ALL SELECT m.id, '405 STi' FROM makes m WHERE m.name = 'Peugeot'
UNION ALL SELECT m.id, '406' FROM makes m WHERE m.name = 'Peugeot'
UNION ALL SELECT m.id, '407' FROM makes m WHERE m.name = 'Peugeot'
UNION ALL SELECT m.id, '408' FROM makes m WHERE m.name = 'Peugeot'
UNION ALL SELECT m.id, '504' FROM makes m WHERE m.name = 'Peugeot'
UNION ALL SELECT m.id, '505' FROM makes m WHERE m.name = 'Peugeot'
UNION ALL SELECT m.id, '508' FROM makes m WHERE m.name = 'Peugeot'
UNION ALL SELECT m.id, '2008' FROM makes m WHERE m.name = 'Peugeot'
UNION ALL SELECT m.id, '3008' FROM makes m WHERE m.name = 'Peugeot'
UNION ALL SELECT m.id, '5008' FROM makes m WHERE m.name = 'Peugeot'
UNION ALL SELECT m.id, 'Partner' FROM makes m WHERE m.name = 'Peugeot'
UNION ALL SELECT m.id, 'Partner Patagónica' FROM makes m WHERE m.name = 'Peugeot'
UNION ALL SELECT m.id, 'Partner Furgón' FROM makes m WHERE m.name = 'Peugeot'
UNION ALL SELECT m.id, 'Expert' FROM makes m WHERE m.name = 'Peugeot'
UNION ALL SELECT m.id, 'Rifter' FROM makes m WHERE m.name = 'Peugeot'
UNION ALL SELECT m.id, 'Traveller' FROM makes m WHERE m.name = 'Peugeot'
UNION ALL SELECT m.id, 'Boxer' FROM makes m WHERE m.name = 'Peugeot';

-- RENAULT
-- RENAULT: Modelos históricos, actuales, variantes y utilitarios en Argentina
INSERT IGNORE INTO makes (name) VALUES ('Renault');
INSERT IGNORE INTO models (make_id, name)
SELECT m.id, '4' FROM makes m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, '6' FROM makes m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, '9' FROM makes m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, '11' FROM makes m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, '12' FROM makes m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, '18' FROM makes m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, '19' FROM makes m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, '21' FROM makes m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, 'Fuego' FROM makes m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, 'Twingo' FROM makes m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, 'Clio' FROM makes m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, 'Clio Mío' FROM makes m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, 'Clio II' FROM makes m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, 'Clio Campus' FROM makes m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, 'Symbol' FROM makes m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, 'Sandero' FROM makes m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, 'Sandero Stepway' FROM makes m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, 'Logan' FROM makes m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, 'Kwid' FROM makes m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, 'Duster' FROM makes m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, 'Duster Oroch' FROM makes m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, 'Captur' FROM makes m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, 'Alaskan' FROM makes m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, 'Koleos' FROM makes m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, 'Fluence' FROM makes m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, 'Megane' FROM makes m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, 'Megane II' FROM makes m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, 'Megane III' FROM makes m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, 'Scenic' FROM makes m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, 'Grand Scenic' FROM makes m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, 'Laguna' FROM makes m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, 'Latitude' FROM makes m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, 'Talisman' FROM makes m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, 'Express' FROM makes m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, 'Kangoo' FROM makes m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, 'Kangoo Express' FROM makes m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, 'Kangoo Stepway' FROM makes m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, 'Master' FROM makes m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, 'Trafic' FROM makes m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, 'Twizy' FROM makes m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, 'ZOE' FROM makes m WHERE m.name = 'Renault';

-- Script completo de marcas y modelos de autos del mercado argentino
-- PARTE 5: Marcas S-Z

-- TOYOTA
-- TOYOTA: Modelos históricos, actuales, variantes y utilitarios en Argentina
INSERT IGNORE INTO makes (name) VALUES ('Toyota');
INSERT IGNORE INTO models (make_id, name)
SELECT m.id, 'Corolla' FROM makes m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Corolla XLi' FROM makes m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Corolla XEi' FROM makes m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Corolla SEG' FROM makes m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Corolla Cross' FROM makes m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Corolla Cross XLi' FROM makes m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Corolla Cross SEG Hybrid' FROM makes m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Yaris' FROM makes m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Yaris XS' FROM makes m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Yaris XLS' FROM makes m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Yaris S' FROM makes m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Etios' FROM makes m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Etios X' FROM makes m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Etios XLS' FROM makes m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Etios Cross' FROM makes m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Camry' FROM makes m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Camry XLE' FROM makes m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Camry Hybrid' FROM makes m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Prius' FROM makes m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Prius Hybrid' FROM makes m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Hilux' FROM makes m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Hilux DX' FROM makes m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Hilux SR' FROM makes m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Hilux SRV' FROM makes m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Hilux SRX' FROM makes m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Hilux Limited' FROM makes m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Hilux GR-S' FROM makes m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'SW4' FROM makes m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'SW4 SR' FROM makes m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'SW4 SRV' FROM makes m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'SW4 SRX' FROM makes m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'RAV4' FROM makes m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'RAV4 Hybrid' FROM makes m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Land Cruiser' FROM makes m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Land Cruiser Prado' FROM makes m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Land Cruiser 200' FROM makes m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, '4Runner' FROM makes m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, '4Runner SR5' FROM makes m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'C-HR' FROM makes m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'C-HR Hybrid' FROM makes m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Avanza' FROM makes m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Innova' FROM makes m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Hiace' FROM makes m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Hiace Commuter' FROM makes m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Commuter' FROM makes m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'FJ Cruiser' FROM makes m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Tercel' FROM makes m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Corona' FROM makes m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Crown' FROM makes m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Sprinter' FROM makes m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Celica' FROM makes m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'MR2' FROM makes m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Supra' FROM makes m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, '86' FROM makes m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Yaris GR' FROM makes m WHERE m.name = 'Toyota';

-- VOLKSWAGEN
-- VOLKSWAGEN: Modelos históricos, actuales, variantes y utilitarios en Argentina
INSERT IGNORE INTO makes (name) VALUES ('Volkswagen');
INSERT IGNORE INTO models (make_id, name)
SELECT m.id, 'Escarabajo' FROM makes m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Sedán' FROM makes m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Kombi' FROM makes m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Brasilia' FROM makes m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, '1500' FROM makes m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Gacel' FROM makes m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Senda' FROM makes m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Carat' FROM makes m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Gol' FROM makes m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Gol Power' FROM makes m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Gol Trend' FROM makes m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Gol Country' FROM makes m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Saveiro' FROM makes m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Saveiro Cross' FROM makes m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Voyage' FROM makes m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Fox' FROM makes m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Surán' FROM makes m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'CrossFox' FROM makes m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'SpaceFox' FROM makes m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Up!' FROM makes m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Polo' FROM makes m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Polo Classic' FROM makes m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Polo GTS' FROM makes m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Virtus' FROM makes m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Nivus' FROM makes m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'T-Cross' FROM makes m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Taos' FROM makes m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Tiguan' FROM makes m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Tiguan Allspace' FROM makes m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Touareg' FROM makes m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Amarok' FROM makes m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Amarok V6' FROM makes m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Caddy' FROM makes m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Transporter' FROM makes m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Multivan' FROM makes m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'California' FROM makes m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Passat' FROM makes m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Passat Variant' FROM makes m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Vento' FROM makes m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Vento GLI' FROM makes m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Jetta' FROM makes m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Golf' FROM makes m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Golf GTI' FROM makes m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Golf Variant' FROM makes m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Golf Country' FROM makes m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Bora' FROM makes m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Santana' FROM makes m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Pointer' FROM makes m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Sharan' FROM makes m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Beetle' FROM makes m WHERE m.name = 'Volkswagen';

-- OTRAS MARCAS RELEVANTES

-- SUZUKI
INSERT IGNORE INTO makes (name) VALUES ('Suzuki');
INSERT IGNORE INTO models (make_id, name)
SELECT m.id, 'Swift' FROM makes m WHERE m.name = 'Suzuki'
UNION ALL SELECT m.id, 'Baleno' FROM makes m WHERE m.name = 'Suzuki'
UNION ALL SELECT m.id, 'Vitara' FROM makes m WHERE m.name = 'Suzuki'
UNION ALL SELECT m.id, 'Jimny' FROM makes m WHERE m.name = 'Suzuki'
UNION ALL SELECT m.id, 'S-Cross' FROM makes m WHERE m.name = 'Suzuki'
UNION ALL SELECT m.id, 'Grand Vitara' FROM makes m WHERE m.name = 'Suzuki'
UNION ALL SELECT m.id, 'Fun' FROM makes m WHERE m.name = 'Suzuki'
UNION ALL SELECT m.id, 'APV' FROM makes m WHERE m.name = 'Suzuki';

-- CHERY
INSERT IGNORE INTO makes (name) VALUES ('Chery');
INSERT IGNORE INTO models (make_id, name)
SELECT m.id, 'QQ' FROM makes m WHERE m.name = 'Chery'
UNION ALL SELECT m.id, 'Tiggo' FROM makes m WHERE m.name = 'Chery'
UNION ALL SELECT m.id, 'Tiggo 2' FROM makes m WHERE m.name = 'Chery'
UNION ALL SELECT m.id, 'Tiggo 3' FROM makes m WHERE m.name = 'Chery'
UNION ALL SELECT m.id, 'Tiggo 4' FROM makes m WHERE m.name = 'Chery'
UNION ALL SELECT m.id, 'Tiggo 5' FROM makes m WHERE m.name = 'Chery'
UNION ALL SELECT m.id, 'Tiggo 7' FROM makes m WHERE m.name = 'Chery'
UNION ALL SELECT m.id, 'Tiggo 8' FROM makes m WHERE m.name = 'Chery'
UNION ALL SELECT m.id, 'Arrizo 5' FROM makes m WHERE m.name = 'Chery'
UNION ALL SELECT m.id, 'Arrizo 7' FROM makes m WHERE m.name = 'Chery';

-- GEELY
INSERT IGNORE INTO makes (name) VALUES ('Geely');
INSERT IGNORE INTO models (make_id, name)
SELECT m.id, 'Emgrand' FROM makes m WHERE m.name = 'Geely'
UNION ALL SELECT m.id, 'Emgrand GS' FROM makes m WHERE m.name = 'Geely'
UNION ALL SELECT m.id, 'Emgrand X7' FROM makes m WHERE m.name = 'Geely'
UNION ALL SELECT m.id, 'Coolray' FROM makes m WHERE m.name = 'Geely'
UNION ALL SELECT m.id, 'Okavango' FROM makes m WHERE m.name = 'Geely';

-- HAVAL
INSERT IGNORE INTO makes (name) VALUES ('Haval');
INSERT IGNORE INTO models (make_id, name)
SELECT m.id, 'H1' FROM makes m WHERE m.name = 'Haval'
UNION ALL SELECT m.id, 'H2' FROM makes m WHERE m.name = 'Haval'
UNION ALL SELECT m.id, 'H6' FROM makes m WHERE m.name = 'Haval'
UNION ALL SELECT m.id, 'H9' FROM makes m WHERE m.name = 'Haval';

-- JAC
INSERT IGNORE INTO makes (name) VALUES ('JAC');
INSERT IGNORE INTO models (make_id, name)
SELECT m.id, 'S2' FROM makes m WHERE m.name = 'JAC'
UNION ALL SELECT m.id, 'S3' FROM makes m WHERE m.name = 'JAC'
UNION ALL SELECT m.id, 'S5' FROM makes m WHERE m.name = 'JAC'
UNION ALL SELECT m.id, 'T6' FROM makes m WHERE m.name = 'JAC'
UNION ALL SELECT m.id, 'T8' FROM makes m WHERE m.name = 'JAC';

-- BAIC
INSERT IGNORE INTO makes (name) VALUES ('BAIC');
INSERT IGNORE INTO models (make_id, name)
SELECT m.id, 'X25' FROM makes m WHERE m.name = 'BAIC'
UNION ALL SELECT m.id, 'X35' FROM makes m WHERE m.name = 'BAIC'
UNION ALL SELECT m.id, 'X55' FROM makes m WHERE m.name = 'BAIC'
UNION ALL SELECT m.id, 'X65' FROM makes m WHERE m.name = 'BAIC';

-- DFSK
INSERT IGNORE INTO makes (name) VALUES ('DFSK');
INSERT IGNORE INTO models (make_id, name)
SELECT m.id, 'Glory 500' FROM makes m WHERE m.name = 'DFSK'
UNION ALL SELECT m.id, 'Glory 560' FROM makes m WHERE m.name = 'DFSK'
UNION ALL SELECT m.id, 'Glory 580' FROM makes m WHERE m.name = 'DFSK'
UNION ALL SELECT m.id, 'C31' FROM makes m WHERE m.name = 'DFSK'
UNION ALL SELECT m.id, 'C32' FROM makes m WHERE m.name = 'DFSK'
UNION ALL SELECT m.id, 'C35' FROM makes m WHERE m.name = 'DFSK'
UNION ALL SELECT m.id, 'K01' FROM makes m WHERE m.name = 'DFSK'
UNION ALL SELECT m.id, 'K02' FROM makes m WHERE m.name = 'DFSK'
UNION ALL SELECT m.id, 'K05' FROM makes m WHERE m.name = 'DFSK'
UNION ALL SELECT m.id, 'K07' FROM makes m WHERE m.name = 'DFSK';
