-- Script completo de marcas y modelos de autos del mercado argentino
-- PARTE 1: Marcas A-C

DELETE FROM MODELS;
DELETE FROM MAKES;

-- ALFA ROMEO
INSERT IGNORE INTO MAKES (name) VALUES ('Alfa Romeo');
INSERT IGNORE INTO MODELS (make_id, name)
SELECT m.id, '147' FROM MAKES m WHERE m.name = 'Alfa Romeo'
UNION ALL SELECT m.id, '156' FROM MAKES m WHERE m.name = 'Alfa Romeo'
UNION ALL SELECT m.id, '159' FROM MAKES m WHERE m.name = 'Alfa Romeo'
UNION ALL SELECT m.id, '166' FROM MAKES m WHERE m.name = 'Alfa Romeo'
UNION ALL SELECT m.id, 'Brera' FROM MAKES m WHERE m.name = 'Alfa Romeo'
UNION ALL SELECT m.id, 'Giulietta' FROM MAKES m WHERE m.name = 'Alfa Romeo'
UNION ALL SELECT m.id, 'Giulia' FROM MAKES m WHERE m.name = 'Alfa Romeo'
UNION ALL SELECT m.id, 'Stelvio' FROM MAKES m WHERE m.name = 'Alfa Romeo'
UNION ALL SELECT m.id, 'Tonale' FROM MAKES m WHERE m.name = 'Alfa Romeo';

-- AUDI
-- AUDI con modelos específicos
INSERT IGNORE INTO MAKES (name) VALUES ('Audi');
INSERT IGNORE INTO MODELS (make_id, name)
SELECT m.id, 'A1 1.4 TFSI' FROM MAKES m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'A1 1.0 TFSI' FROM MAKES m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'A3 1.4 TFSI' FROM MAKES m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'A3 2.0 TFSI' FROM MAKES m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'A3 1.6 TDI' FROM MAKES m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'A3 2.0 TDI' FROM MAKES m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'A4 1.4 TFSI' FROM MAKES m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'A4 2.0 TFSI' FROM MAKES m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'A4 2.0 TDI' FROM MAKES m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'A5 2.0 TFSI' FROM MAKES m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'A5 2.0 TDI' FROM MAKES m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'A6 2.0 TFSI' FROM MAKES m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'A6 2.0 TDI' FROM MAKES m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'A6 3.0 TDI' FROM MAKES m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'A7 3.0 TFSI' FROM MAKES m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'A7 3.0 TDI' FROM MAKES m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'A8 4.0 TFSI' FROM MAKES m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'A8 3.0 TDI' FROM MAKES m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'Q2 1.0 TFSI' FROM MAKES m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'Q2 1.4 TFSI' FROM MAKES m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'Q3 1.4 TFSI' FROM MAKES m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'Q3 2.0 TFSI' FROM MAKES m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'Q3 2.0 TDI' FROM MAKES m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'Q5 2.0 TFSI' FROM MAKES m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'Q5 2.0 TDI' FROM MAKES m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'Q5 3.0 TDI' FROM MAKES m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'Q7 3.0 TFSI' FROM MAKES m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'Q7 3.0 TDI' FROM MAKES m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'Q8 3.0 TFSI' FROM MAKES m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'Q8 3.0 TDI' FROM MAKES m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'TT 2.0 TFSI' FROM MAKES m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'TT RS' FROM MAKES m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'RS3' FROM MAKES m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'RS4' FROM MAKES m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'RS5' FROM MAKES m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'RS6' FROM MAKES m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'RS7' FROM MAKES m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'S3' FROM MAKES m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'S4' FROM MAKES m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'S5' FROM MAKES m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'S6' FROM MAKES m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'S7' FROM MAKES m WHERE m.name = 'Audi'
UNION ALL SELECT m.id, 'S8' FROM MAKES m WHERE m.name = 'Audi';

-- BMW
-- BMW con modelos específicos
INSERT IGNORE INTO MAKES (name) VALUES ('BMW');
INSERT IGNORE INTO MODELS (make_id, name)
SELECT m.id, '116i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '118i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '120i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '125i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '130i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '135i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'M135i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'M140i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '218i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '220i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '225i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '228i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '230i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '235i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '240i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'M235i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'M240i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '316i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '318i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '320i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '323i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '325i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '328i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '330i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '335i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '340i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'M3' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'M340i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '420i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '425i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '428i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '430i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '435i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '440i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'M4' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'M440i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '520i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '523i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '525i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '528i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '530i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '535i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '540i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '545i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '550i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'M5' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'M550i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '640i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '650i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'M6' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '730i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '740i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '750i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '760i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'M760i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '840i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, '850i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'M8' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'X1 sDrive18i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'X1 xDrive20i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'X1 xDrive25i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'X2 sDrive18i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'X2 xDrive20i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'X2 M35i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'X3 xDrive20i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'X3 xDrive30i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'X3 M40i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'X3 M' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'X4 xDrive20i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'X4 xDrive30i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'X4 M40i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'X4 M' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'X5 xDrive40i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'X5 xDrive50i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'X5 M50i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'X5 M' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'X6 xDrive40i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'X6 xDrive50i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'X6 M50i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'X6 M' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'X7 xDrive40i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'X7 xDrive50i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'X7 M50i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'Z4 sDrive20i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'Z4 sDrive30i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'Z4 M40i' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'i3' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'i4 eDrive40' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'i4 M50' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'i7 xDrive60' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'iX xDrive50' FROM MAKES m WHERE m.name = 'BMW'
UNION ALL SELECT m.id, 'iX M60' FROM MAKES m WHERE m.name = 'BMW';

-- CITROËN
-- CITROËN: Modelos históricos, actuales, variantes y utilitarios en Argentina
INSERT IGNORE INTO MAKES (name) VALUES ('Citroën');
INSERT IGNORE INTO MODELS (make_id, name)
SELECT m.id, '2CV' FROM MAKES m WHERE m.name = 'Citroën'
UNION ALL SELECT m.id, '3CV' FROM MAKES m WHERE m.name = 'Citroën'
UNION ALL SELECT m.id, 'Ami 8' FROM MAKES m WHERE m.name = 'Citroën'
UNION ALL SELECT m.id, 'Mehari' FROM MAKES m WHERE m.name = 'Citroën'
UNION ALL SELECT m.id, 'Visa' FROM MAKES m WHERE m.name = 'Citroën'
UNION ALL SELECT m.id, 'BX' FROM MAKES m WHERE m.name = 'Citroën'
UNION ALL SELECT m.id, 'ZX' FROM MAKES m WHERE m.name = 'Citroën'
UNION ALL SELECT m.id, 'Xsara' FROM MAKES m WHERE m.name = 'Citroën'
UNION ALL SELECT m.id, 'Xsara Picasso' FROM MAKES m WHERE m.name = 'Citroën'
UNION ALL SELECT m.id, 'C3' FROM MAKES m WHERE m.name = 'Citroën'
UNION ALL SELECT m.id, 'C3 Aircross' FROM MAKES m WHERE m.name = 'Citroën'
UNION ALL SELECT m.id, 'C3 Picasso' FROM MAKES m WHERE m.name = 'Citroën'
UNION ALL SELECT m.id, 'C4' FROM MAKES m WHERE m.name = 'Citroën'
UNION ALL SELECT m.id, 'C4 Lounge' FROM MAKES m WHERE m.name = 'Citroën'
UNION ALL SELECT m.id, 'C4 Cactus' FROM MAKES m WHERE m.name = 'Citroën'
UNION ALL SELECT m.id, 'C4 Picasso' FROM MAKES m WHERE m.name = 'Citroën'
UNION ALL SELECT m.id, 'C5' FROM MAKES m WHERE m.name = 'Citroën'
UNION ALL SELECT m.id, 'C5 Aircross' FROM MAKES m WHERE m.name = 'Citroën'
UNION ALL SELECT m.id, 'Berlingo' FROM MAKES m WHERE m.name = 'Citroën'
UNION ALL SELECT m.id, 'Berlingo Multispace' FROM MAKES m WHERE m.name = 'Citroën'
UNION ALL SELECT m.id, 'Berlingo Furgón' FROM MAKES m WHERE m.name = 'Citroën'
UNION ALL SELECT m.id, 'Jumpy' FROM MAKES m WHERE m.name = 'Citroën'
UNION ALL SELECT m.id, 'Jumper' FROM MAKES m WHERE m.name = 'Citroën'
UNION ALL SELECT m.id, 'Nemo' FROM MAKES m WHERE m.name = 'Citroën'
UNION ALL SELECT m.id, 'C-Elysée' FROM MAKES m WHERE m.name = 'Citroën'
UNION ALL SELECT m.id, 'C1' FROM MAKES m WHERE m.name = 'Citroën'
UNION ALL SELECT m.id, 'C2' FROM MAKES m WHERE m.name = 'Citroën'
UNION ALL SELECT m.id, 'C6' FROM MAKES m WHERE m.name = 'Citroën'
UNION ALL SELECT m.id, 'DS3' FROM MAKES m WHERE m.name = 'Citroën'
UNION ALL SELECT m.id, 'DS4' FROM MAKES m WHERE m.name = 'Citroën'
UNION ALL SELECT m.id, 'DS5' FROM MAKES m WHERE m.name = 'Citroën'
UNION ALL SELECT m.id, 'C-Zero' FROM MAKES m WHERE m.name = 'Citroën'
UNION ALL SELECT m.id, 'E-C4' FROM MAKES m WHERE m.name = 'Citroën'
UNION ALL SELECT m.id, 'E-Berlingo' FROM MAKES m WHERE m.name = 'Citroën';

-- Script completo de marcas y modelos de autos del mercado argentino
-- PARTE 2: Marcas D-F

-- DACIA
INSERT IGNORE INTO MAKES (name) VALUES ('Dacia');
INSERT IGNORE INTO MODELS (make_id, name)
SELECT m.id, 'Sandero' FROM MAKES m WHERE m.name = 'Dacia'
UNION ALL SELECT m.id, 'Logan' FROM MAKES m WHERE m.name = 'Dacia'
UNION ALL SELECT m.id, 'Duster' FROM MAKES m WHERE m.name = 'Dacia'
UNION ALL SELECT m.id, 'Spring' FROM MAKES m WHERE m.name = 'Dacia'
UNION ALL SELECT m.id, 'Jogger' FROM MAKES m WHERE m.name = 'Dacia'
UNION ALL SELECT m.id, 'Dokker' FROM MAKES m WHERE m.name = 'Dacia'
UNION ALL SELECT m.id, 'Lodgy' FROM MAKES m WHERE m.name = 'Dacia'
UNION ALL SELECT m.id, 'Pickup' FROM MAKES m WHERE m.name = 'Dacia';

-- FIAT
-- FIAT: Modelos históricos, actuales, variantes y utilitarios en Argentina
INSERT IGNORE INTO MAKES (name) VALUES ('Fiat');
INSERT IGNORE INTO MODELS (make_id, name)
SELECT m.id, '600' FROM MAKES m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, '800' FROM MAKES m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, '1100' FROM MAKES m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, '128' FROM MAKES m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, '147' FROM MAKES m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Duna' FROM MAKES m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Duna Weekend' FROM MAKES m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Uno' FROM MAKES m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Uno Fire' FROM MAKES m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Uno Way' FROM MAKES m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Spazio' FROM MAKES m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Regatta' FROM MAKES m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Siena' FROM MAKES m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Siena EL' FROM MAKES m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Siena Fire' FROM MAKES m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Palio' FROM MAKES m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Palio Fire' FROM MAKES m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Palio Adventure' FROM MAKES m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Palio Weekend' FROM MAKES m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Palio EL' FROM MAKES m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Palio HL' FROM MAKES m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Palio Sporting' FROM MAKES m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Palio Attractive' FROM MAKES m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Palio Essence' FROM MAKES m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Palio 1.3' FROM MAKES m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Palio 1.4' FROM MAKES m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Palio 1.6' FROM MAKES m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Palio 1.8' FROM MAKES m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Punto' FROM MAKES m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Punto Attractive' FROM MAKES m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Punto Essence' FROM MAKES m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Punto Sporting' FROM MAKES m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Linea' FROM MAKES m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Idea' FROM MAKES m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Idea Adventure' FROM MAKES m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Mobi' FROM MAKES m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Mobi Easy' FROM MAKES m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Mobi Like' FROM MAKES m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Mobi Way' FROM MAKES m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Argo' FROM MAKES m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Argo Drive' FROM MAKES m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Argo Precision' FROM MAKES m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Argo Trekking' FROM MAKES m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Cronos' FROM MAKES m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Cronos Drive' FROM MAKES m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Cronos Precision' FROM MAKES m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Strada' FROM MAKES m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Strada Working' FROM MAKES m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Strada Adventure' FROM MAKES m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Strada Freedom' FROM MAKES m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Strada Volcano' FROM MAKES m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Toro' FROM MAKES m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Toro Freedom' FROM MAKES m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Toro Volcano' FROM MAKES m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Toro Ranch' FROM MAKES m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, '500' FROM MAKES m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, '500 Lounge' FROM MAKES m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, '500 Sport' FROM MAKES m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, '500X' FROM MAKES m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, '500L' FROM MAKES m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Fiorino' FROM MAKES m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Fiorino Furgón' FROM MAKES m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Ducato' FROM MAKES m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Ducato Maxi' FROM MAKES m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Ducato Minibus' FROM MAKES m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Qubo' FROM MAKES m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Doblo' FROM MAKES m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Doblo Adventure' FROM MAKES m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Palio Weekend Adventure' FROM MAKES m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Palio Weekend Trekking' FROM MAKES m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Palio Weekend ELX' FROM MAKES m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Palio Weekend HL' FROM MAKES m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Palio Weekend Stile' FROM MAKES m WHERE m.name = 'Fiat'
UNION ALL SELECT m.id, 'Palio Weekend Locker' FROM MAKES m WHERE m.name = 'Fiat';

-- FORD

-- FORD: Modelos históricos, actuales, variantes y utilitarios en Argentina
INSERT IGNORE INTO MAKES (name) VALUES ('Ford');
INSERT IGNORE INTO MODELS (make_id, name)
SELECT m.id, 'Falcon' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Taunus' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Sierra' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Escort' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Fiesta' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Fiesta Max' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Fiesta One' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Fiesta KD' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Focus' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Focus II' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Focus III' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Focus Trend' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Focus Titanium' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Ka' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Ka+ (Ka Plus)' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Ka Freestyle' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Mondeo' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Mondeo Vignale' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Mondeo Titanium' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Mondeo Ghia' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Mondeo LX' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Orion' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Fiesta Kinetic' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'EcoSport' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'EcoSport 2da generación' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'EcoSport Freestyle' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'EcoSport Titanium' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Kuga' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Kuga Hybrid' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Territory' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Territory Titanium' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Ranger' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Ranger XL' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Ranger XLS' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Ranger XLT' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Ranger Limited' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Ranger Raptor' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'F-100' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'F-150' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'F-150 Lariat' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'F-150 Raptor' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Courier' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Transit' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Transit Custom' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Transit Connect' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Galaxy' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'S-Max' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'B-Max' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'C-Max' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Escape' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Edge' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Explorer' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Expedition' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Bronco' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Mustang' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Mustang GT' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Mustang Mach 1' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Mustang Mach-E' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Fairlane' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'LTD' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Custom' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Deluxe' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Granada' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Scorpio' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Laser' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Courier Van' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Pampa' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'F-350' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'F-4000' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Super Duty' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Ranger Cabina Simple' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Ranger Cabina Doble' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Ranger Limited Plus' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Ranger Storm' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Ranger Black Edition' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Ranger FX4' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Ranger Wildtrak' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Ranger Thunder' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Ranger Limited 3.2' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Ranger XLS 2.2' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Ranger XLT 3.2' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Ranger XLT 2.2' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Ranger XL 2.2' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Ranger XL 3.2' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Ranger Limited 2.2' FROM MAKES m WHERE m.name = 'Ford'
UNION ALL SELECT m.id, 'Ranger Limited 3.2' FROM MAKES m WHERE m.name = 'Ford';
-- CHEVROLET con modelos específicos
-- CHEVROLET: Modelos históricos, actuales, variantes y utilitarios en Argentina
INSERT IGNORE INTO MAKES (name) VALUES ('Chevrolet');
INSERT IGNORE INTO MODELS (make_id, name)
SELECT m.id, 'Corsa' FROM MAKES m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Corsa II' FROM MAKES m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Corsa Classic' FROM MAKES m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Corsa Wagon' FROM MAKES m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Celta' FROM MAKES m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Astra' FROM MAKES m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Astra GSi' FROM MAKES m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Vectra' FROM MAKES m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Vectra GT' FROM MAKES m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Meriva' FROM MAKES m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Zafira' FROM MAKES m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Aveo' FROM MAKES m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Sonic' FROM MAKES m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Onix' FROM MAKES m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Onix Joy' FROM MAKES m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Onix Plus' FROM MAKES m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Prisma' FROM MAKES m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Prisma Joy' FROM MAKES m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Cruze' FROM MAKES m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Cruze 5' FROM MAKES m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Spin' FROM MAKES m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Spin Activ' FROM MAKES m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Tracker' FROM MAKES m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Tracker Turbo' FROM MAKES m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Captiva' FROM MAKES m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'S10' FROM MAKES m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'S10 High Country' FROM MAKES m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Montana' FROM MAKES m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Blazer' FROM MAKES m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Silverado' FROM MAKES m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Camaro' FROM MAKES m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Camaro SS' FROM MAKES m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Corvette' FROM MAKES m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Malibu' FROM MAKES m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Impala' FROM MAKES m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'C-10' FROM MAKES m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'D-20' FROM MAKES m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'LUV' FROM MAKES m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Sprint' FROM MAKES m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'C-20' FROM MAKES m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'C-30' FROM MAKES m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, '400' FROM MAKES m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Chevy' FROM MAKES m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Super' FROM MAKES m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Nova' FROM MAKES m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Monza' FROM MAKES m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Opala' FROM MAKES m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Kadett' FROM MAKES m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Ipanema' FROM MAKES m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Corsa Wagon' FROM MAKES m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Corsa Pick-Up' FROM MAKES m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Corsa Utility' FROM MAKES m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Corsa Classic' FROM MAKES m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Corsa II 1.8' FROM MAKES m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Corsa II 1.4' FROM MAKES m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Corsa II 1.6' FROM MAKES m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Corsa Classic 1.4' FROM MAKES m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Corsa Classic 1.6' FROM MAKES m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Corsa Classic 1.7 Diesel' FROM MAKES m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Corsa Wagon 1.6' FROM MAKES m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Corsa Wagon 1.4' FROM MAKES m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Corsa Pick-Up 1.7 Diesel' FROM MAKES m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Corsa Pick-Up 1.6' FROM MAKES m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Corsa Utility 1.7 Diesel' FROM MAKES m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Corsa Utility 1.6' FROM MAKES m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Corsa Utility 1.4' FROM MAKES m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Corsa Utility 1.8' FROM MAKES m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Corsa Utility 1.3' FROM MAKES m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Corsa Utility 1.2' FROM MAKES m WHERE m.name = 'Chevrolet'
UNION ALL SELECT m.id, 'Corsa Utility 1.0' FROM MAKES m WHERE m.name = 'Chevrolet';

-- Script completo de marcas y modelos de autos del mercado argentino
-- PARTE 3: Marcas H-L

-- HONDA
-- HONDA: Modelos históricos, actuales, variantes y SUV en Argentina
INSERT IGNORE INTO MAKES (name) VALUES ('Honda');
INSERT IGNORE INTO MODELS (make_id, name)
SELECT m.id, 'Civic' FROM MAKES m WHERE m.name = 'Honda'
UNION ALL SELECT m.id, 'Civic EX' FROM MAKES m WHERE m.name = 'Honda'
UNION ALL SELECT m.id, 'Civic EXS' FROM MAKES m WHERE m.name = 'Honda'
UNION ALL SELECT m.id, 'Civic LXS' FROM MAKES m WHERE m.name = 'Honda'
UNION ALL SELECT m.id, 'Civic SI' FROM MAKES m WHERE m.name = 'Honda'
UNION ALL SELECT m.id, 'Civic Type R' FROM MAKES m WHERE m.name = 'Honda'
UNION ALL SELECT m.id, 'City' FROM MAKES m WHERE m.name = 'Honda'
UNION ALL SELECT m.id, 'City EX' FROM MAKES m WHERE m.name = 'Honda'
UNION ALL SELECT m.id, 'City EXL' FROM MAKES m WHERE m.name = 'Honda'
UNION ALL SELECT m.id, 'Fit' FROM MAKES m WHERE m.name = 'Honda'
UNION ALL SELECT m.id, 'Fit EX' FROM MAKES m WHERE m.name = 'Honda'
UNION ALL SELECT m.id, 'Fit EXL' FROM MAKES m WHERE m.name = 'Honda'
UNION ALL SELECT m.id, 'WR-V' FROM MAKES m WHERE m.name = 'Honda'
UNION ALL SELECT m.id, 'HR-V' FROM MAKES m WHERE m.name = 'Honda'
UNION ALL SELECT m.id, 'HR-V EX' FROM MAKES m WHERE m.name = 'Honda'
UNION ALL SELECT m.id, 'HR-V EXL' FROM MAKES m WHERE m.name = 'Honda'
UNION ALL SELECT m.id, 'CR-V' FROM MAKES m WHERE m.name = 'Honda'
UNION ALL SELECT m.id, 'CR-V EX' FROM MAKES m WHERE m.name = 'Honda'
UNION ALL SELECT m.id, 'CR-V EXL' FROM MAKES m WHERE m.name = 'Honda'
UNION ALL SELECT m.id, 'CR-V Touring' FROM MAKES m WHERE m.name = 'Honda'
UNION ALL SELECT m.id, 'Pilot' FROM MAKES m WHERE m.name = 'Honda'
UNION ALL SELECT m.id, 'Odyssey' FROM MAKES m WHERE m.name = 'Honda'
UNION ALL SELECT m.id, 'Ridgeline' FROM MAKES m WHERE m.name = 'Honda';

-- HYUNDAI
-- HYUNDAI: Modelos históricos, actuales, variantes y SUV en Argentina
INSERT IGNORE INTO MAKES (name) VALUES ('Hyundai');
INSERT IGNORE INTO MODELS (make_id, name)
SELECT m.id, 'Accent' FROM MAKES m WHERE m.name = 'Hyundai'
UNION ALL SELECT m.id, 'Atos' FROM MAKES m WHERE m.name = 'Hyundai'
UNION ALL SELECT m.id, 'Creta' FROM MAKES m WHERE m.name = 'Hyundai'
UNION ALL SELECT m.id, 'Elantra' FROM MAKES m WHERE m.name = 'Hyundai'
UNION ALL SELECT m.id, 'Grand i10' FROM MAKES m WHERE m.name = 'Hyundai'
UNION ALL SELECT m.id, 'HB20' FROM MAKES m WHERE m.name = 'Hyundai'
UNION ALL SELECT m.id, 'i10' FROM MAKES m WHERE m.name = 'Hyundai'
UNION ALL SELECT m.id, 'i20' FROM MAKES m WHERE m.name = 'Hyundai'
UNION ALL SELECT m.id, 'i30' FROM MAKES m WHERE m.name = 'Hyundai'
UNION ALL SELECT m.id, 'i35' FROM MAKES m WHERE m.name = 'Hyundai'
UNION ALL SELECT m.id, 'Kona' FROM MAKES m WHERE m.name = 'Hyundai'
UNION ALL SELECT m.id, 'Santa Fe' FROM MAKES m WHERE m.name = 'Hyundai'
UNION ALL SELECT m.id, 'Santa Fe XL' FROM MAKES m WHERE m.name = 'Hyundai'
UNION ALL SELECT m.id, 'Tucson' FROM MAKES m WHERE m.name = 'Hyundai'
UNION ALL SELECT m.id, 'Venue' FROM MAKES m WHERE m.name = 'Hyundai'
UNION ALL SELECT m.id, 'Veloster' FROM MAKES m WHERE m.name = 'Hyundai'
UNION ALL SELECT m.id, 'Verna' FROM MAKES m WHERE m.name = 'Hyundai'
UNION ALL SELECT m.id, 'Sonata' FROM MAKES m WHERE m.name = 'Hyundai'
UNION ALL SELECT m.id, 'Azera' FROM MAKES m WHERE m.name = 'Hyundai'
UNION ALL SELECT m.id, 'H1' FROM MAKES m WHERE m.name = 'Hyundai'
UNION ALL SELECT m.id, 'H100' FROM MAKES m WHERE m.name = 'Hyundai'
UNION ALL SELECT m.id, 'Starex' FROM MAKES m WHERE m.name = 'Hyundai';
-- JEEP
-- JEEP: Modelos históricos, actuales, variantes y SUV en Argentina
INSERT IGNORE INTO MAKES (name) VALUES ('Jeep');
INSERT IGNORE INTO MODELS (make_id, name)
SELECT m.id, 'Renegade' FROM MAKES m WHERE m.name = 'Jeep'
UNION ALL SELECT m.id, 'Compass' FROM MAKES m WHERE m.name = 'Jeep'
UNION ALL SELECT m.id, 'Commander' FROM MAKES m WHERE m.name = 'Jeep'
UNION ALL SELECT m.id, 'Cherokee' FROM MAKES m WHERE m.name = 'Jeep'
UNION ALL SELECT m.id, 'Grand Cherokee' FROM MAKES m WHERE m.name = 'Jeep'
UNION ALL SELECT m.id, 'Wrangler' FROM MAKES m WHERE m.name = 'Jeep'
UNION ALL SELECT m.id, 'Gladiator' FROM MAKES m WHERE m.name = 'Jeep'
UNION ALL SELECT m.id, 'Patriot' FROM MAKES m WHERE m.name = 'Jeep'
UNION ALL SELECT m.id, 'Liberty' FROM MAKES m WHERE m.name = 'Jeep'
UNION ALL SELECT m.id, 'Wagoneer' FROM MAKES m WHERE m.name = 'Jeep'
UNION ALL SELECT m.id, 'CJ-5' FROM MAKES m WHERE m.name = 'Jeep'
UNION ALL SELECT m.id, 'CJ-7' FROM MAKES m WHERE m.name = 'Jeep'
UNION ALL SELECT m.id, 'Willys' FROM MAKES m WHERE m.name = 'Jeep';

-- KIA
-- KIA: Modelos históricos, actuales, variantes y SUV en Argentina
INSERT IGNORE INTO MAKES (name) VALUES ('Kia');
INSERT IGNORE INTO MODELS (make_id, name)
SELECT m.id, 'Picanto' FROM MAKES m WHERE m.name = 'Kia'
UNION ALL SELECT m.id, 'Rio' FROM MAKES m WHERE m.name = 'Kia'
UNION ALL SELECT m.id, 'Cerato' FROM MAKES m WHERE m.name = 'Kia'
UNION ALL SELECT m.id, 'Soul' FROM MAKES m WHERE m.name = 'Kia'
UNION ALL SELECT m.id, 'Seltos' FROM MAKES m WHERE m.name = 'Kia'
UNION ALL SELECT m.id, 'Sportage' FROM MAKES m WHERE m.name = 'Kia'
UNION ALL SELECT m.id, 'Sorento' FROM MAKES m WHERE m.name = 'Kia'
UNION ALL SELECT m.id, 'Carnival' FROM MAKES m WHERE m.name = 'Kia'
UNION ALL SELECT m.id, 'Stinger' FROM MAKES m WHERE m.name = 'Kia'
UNION ALL SELECT m.id, 'Mohave' FROM MAKES m WHERE m.name = 'Kia'
UNION ALL SELECT m.id, 'Optima' FROM MAKES m WHERE m.name = 'Kia'
UNION ALL SELECT m.id, 'Bongo' FROM MAKES m WHERE m.name = 'Kia'
UNION ALL SELECT m.id, 'K2500' FROM MAKES m WHERE m.name = 'Kia'
UNION ALL SELECT m.id, 'K2700' FROM MAKES m WHERE m.name = 'Kia';

-- LAND ROVER
INSERT IGNORE INTO MAKES (name) VALUES ('Land Rover');
INSERT IGNORE INTO MODELS (make_id, name)
SELECT m.id, 'Defender' FROM MAKES m WHERE m.name = 'Land Rover'
UNION ALL SELECT m.id, 'Discovery' FROM MAKES m WHERE m.name = 'Land Rover'
UNION ALL SELECT m.id, 'Discovery Sport' FROM MAKES m WHERE m.name = 'Land Rover'
UNION ALL SELECT m.id, 'Range Rover' FROM MAKES m WHERE m.name = 'Land Rover'
UNION ALL SELECT m.id, 'Range Rover Evoque' FROM MAKES m WHERE m.name = 'Land Rover'
UNION ALL SELECT m.id, 'Range Rover Sport' FROM MAKES m WHERE m.name = 'Land Rover'
UNION ALL SELECT m.id, 'Range Rover Velar' FROM MAKES m WHERE m.name = 'Land Rover'
UNION ALL SELECT m.id, 'Freelander' FROM MAKES m WHERE m.name = 'Land Rover';

-- Script completo de marcas y modelos de autos del mercado argentino
-- PARTE 4: Marcas M-R

-- MERCEDES-BENZ
-- MERCEDES-BENZ con modelos específicos
INSERT IGNORE INTO MAKES (name) VALUES ('Mercedes-Benz');
INSERT IGNORE INTO MODELS (make_id, name)
SELECT m.id, 'A180' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'A200' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'A250' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'A35 AMG' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'A45 AMG' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'B180' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'B200' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'B250' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'C180' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'C200' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'C250' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'C300' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'C350e' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'C400' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'C43 AMG' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'C63 AMG' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'CLA180' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'CLA200' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'CLA250' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'CLA35 AMG' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'CLA45 AMG' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'CLS350' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'CLS400' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'CLS450' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'CLS53 AMG' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'E200' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'E250' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'E300' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'E350' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'E400' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'E450' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'E43 AMG' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'E53 AMG' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'E63 AMG' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'GLA180' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'GLA200' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'GLA250' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'GLA35 AMG' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'GLA45 AMG' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'GLB200' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'GLB250' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'GLB35 AMG' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'GLC200' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'GLC250' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'GLC300' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'GLC43 AMG' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'GLC63 AMG' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'GLE350' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'GLE400' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'GLE450' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'GLE53 AMG' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'GLE63 AMG' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'GLS450' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'GLS580' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'GLS63 AMG' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'S400' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'S450' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'S500' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'S560' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'S580' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'S63 AMG' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'S65 AMG' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'SL400' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'SL500' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'SL63 AMG' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'SL65 AMG' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'Vito' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'Sprinter' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'Clase X' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'GLA' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'GLB' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'GLC' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'GLE' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'GLS' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'EQB' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'EQA' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'EQC' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'EQS' FROM MAKES m WHERE m.name = 'Mercedes-Benz'
UNION ALL SELECT m.id, 'AMG GT' FROM MAKES m WHERE m.name = 'Mercedes-Benz';
-- NISSAN
-- NISSAN: Modelos históricos, actuales, variantes y SUV en Argentina
INSERT IGNORE INTO MAKES (name) VALUES ('Nissan');
INSERT IGNORE INTO MODELS (make_id, name)
SELECT m.id, 'March' FROM MAKES m WHERE m.name = 'Nissan'
UNION ALL SELECT m.id, 'Versa' FROM MAKES m WHERE m.name = 'Nissan'
UNION ALL SELECT m.id, 'Versa Advance' FROM MAKES m WHERE m.name = 'Nissan'
UNION ALL SELECT m.id, 'Versa Exclusive' FROM MAKES m WHERE m.name = 'Nissan'
UNION ALL SELECT m.id, 'Sentra' FROM MAKES m WHERE m.name = 'Nissan'
UNION ALL SELECT m.id, 'Sentra Advance' FROM MAKES m WHERE m.name = 'Nissan'
UNION ALL SELECT m.id, 'Sentra Exclusive' FROM MAKES m WHERE m.name = 'Nissan'
UNION ALL SELECT m.id, 'Tiida' FROM MAKES m WHERE m.name = 'Nissan'
UNION ALL SELECT m.id, 'Note' FROM MAKES m WHERE m.name = 'Nissan'
UNION ALL SELECT m.id, 'Altima' FROM MAKES m WHERE m.name = 'Nissan'
UNION ALL SELECT m.id, '370Z' FROM MAKES m WHERE m.name = 'Nissan'
UNION ALL SELECT m.id, 'Kicks' FROM MAKES m WHERE m.name = 'Nissan'
UNION ALL SELECT m.id, 'Kicks Advance' FROM MAKES m WHERE m.name = 'Nissan'
UNION ALL SELECT m.id, 'Kicks Exclusive' FROM MAKES m WHERE m.name = 'Nissan'
UNION ALL SELECT m.id, 'Qashqai' FROM MAKES m WHERE m.name = 'Nissan'
UNION ALL SELECT m.id, 'X-Trail' FROM MAKES m WHERE m.name = 'Nissan'
UNION ALL SELECT m.id, 'Murano' FROM MAKES m WHERE m.name = 'Nissan'
UNION ALL SELECT m.id, 'Frontier' FROM MAKES m WHERE m.name = 'Nissan'
UNION ALL SELECT m.id, 'Frontier XE' FROM MAKES m WHERE m.name = 'Nissan'
UNION ALL SELECT m.id, 'Frontier LE' FROM MAKES m WHERE m.name = 'Nissan'
UNION ALL SELECT m.id, 'Frontier Platinum' FROM MAKES m WHERE m.name = 'Nissan'
UNION ALL SELECT m.id, 'Navara' FROM MAKES m WHERE m.name = 'Nissan'
UNION ALL SELECT m.id, 'NP300' FROM MAKES m WHERE m.name = 'Nissan'
UNION ALL SELECT m.id, 'Pathfinder' FROM MAKES m WHERE m.name = 'Nissan'
UNION ALL SELECT m.id, 'Patrol' FROM MAKES m WHERE m.name = 'Nissan'
UNION ALL SELECT m.id, 'LEAF' FROM MAKES m WHERE m.name = 'Nissan';

-- PEUGEOT
-- PEUGEOT: Modelos históricos, actuales, variantes y utilitarios en Argentina
INSERT IGNORE INTO MAKES (name) VALUES ('Peugeot');
INSERT IGNORE INTO MODELS (make_id, name)
SELECT m.id, '104' FROM MAKES m WHERE m.name = 'Peugeot'
UNION ALL SELECT m.id, '106' FROM MAKES m WHERE m.name = 'Peugeot'
UNION ALL SELECT m.id, '205' FROM MAKES m WHERE m.name = 'Peugeot'
UNION ALL SELECT m.id, '206' FROM MAKES m WHERE m.name = 'Peugeot'
UNION ALL SELECT m.id, '206 Compact' FROM MAKES m WHERE m.name = 'Peugeot'
UNION ALL SELECT m.id, '207' FROM MAKES m WHERE m.name = 'Peugeot'
UNION ALL SELECT m.id, '207 Compact' FROM MAKES m WHERE m.name = 'Peugeot'
UNION ALL SELECT m.id, '208' FROM MAKES m WHERE m.name = 'Peugeot'
UNION ALL SELECT m.id, '301' FROM MAKES m WHERE m.name = 'Peugeot'
UNION ALL SELECT m.id, '304' FROM MAKES m WHERE m.name = 'Peugeot'
UNION ALL SELECT m.id, '305' FROM MAKES m WHERE m.name = 'Peugeot'
UNION ALL SELECT m.id, '306' FROM MAKES m WHERE m.name = 'Peugeot'
UNION ALL SELECT m.id, '307' FROM MAKES m WHERE m.name = 'Peugeot'
UNION ALL SELECT m.id, '308' FROM MAKES m WHERE m.name = 'Peugeot'
UNION ALL SELECT m.id, '309' FROM MAKES m WHERE m.name = 'Peugeot'
UNION ALL SELECT m.id, '405' FROM MAKES m WHERE m.name = 'Peugeot'
UNION ALL SELECT m.id, '405 SR' FROM MAKES m WHERE m.name = 'Peugeot'
UNION ALL SELECT m.id, '405 SRI' FROM MAKES m WHERE m.name = 'Peugeot'
UNION ALL SELECT m.id, '405 GR' FROM MAKES m WHERE m.name = 'Peugeot'
UNION ALL SELECT m.id, '405 GL' FROM MAKES m WHERE m.name = 'Peugeot'
UNION ALL SELECT m.id, '405 GTX' FROM MAKES m WHERE m.name = 'Peugeot'
UNION ALL SELECT m.id, '405 STi' FROM MAKES m WHERE m.name = 'Peugeot'
UNION ALL SELECT m.id, '406' FROM MAKES m WHERE m.name = 'Peugeot'
UNION ALL SELECT m.id, '407' FROM MAKES m WHERE m.name = 'Peugeot'
UNION ALL SELECT m.id, '408' FROM MAKES m WHERE m.name = 'Peugeot'
UNION ALL SELECT m.id, '504' FROM MAKES m WHERE m.name = 'Peugeot'
UNION ALL SELECT m.id, '505' FROM MAKES m WHERE m.name = 'Peugeot'
UNION ALL SELECT m.id, '508' FROM MAKES m WHERE m.name = 'Peugeot'
UNION ALL SELECT m.id, '2008' FROM MAKES m WHERE m.name = 'Peugeot'
UNION ALL SELECT m.id, '3008' FROM MAKES m WHERE m.name = 'Peugeot'
UNION ALL SELECT m.id, '5008' FROM MAKES m WHERE m.name = 'Peugeot'
UNION ALL SELECT m.id, 'Partner' FROM MAKES m WHERE m.name = 'Peugeot'
UNION ALL SELECT m.id, 'Partner Patagónica' FROM MAKES m WHERE m.name = 'Peugeot'
UNION ALL SELECT m.id, 'Partner Furgón' FROM MAKES m WHERE m.name = 'Peugeot'
UNION ALL SELECT m.id, 'Expert' FROM MAKES m WHERE m.name = 'Peugeot'
UNION ALL SELECT m.id, 'Rifter' FROM MAKES m WHERE m.name = 'Peugeot'
UNION ALL SELECT m.id, 'Traveller' FROM MAKES m WHERE m.name = 'Peugeot'
UNION ALL SELECT m.id, 'Boxer' FROM MAKES m WHERE m.name = 'Peugeot';

-- RENAULT
-- RENAULT: Modelos históricos, actuales, variantes y utilitarios en Argentina
INSERT IGNORE INTO MAKES (name) VALUES ('Renault');
INSERT IGNORE INTO MODELS (make_id, name)
SELECT m.id, '4' FROM MAKES m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, '6' FROM MAKES m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, '9' FROM MAKES m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, '11' FROM MAKES m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, '12' FROM MAKES m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, '18' FROM MAKES m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, '19' FROM MAKES m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, '21' FROM MAKES m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, 'Fuego' FROM MAKES m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, 'Twingo' FROM MAKES m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, 'Clio' FROM MAKES m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, 'Clio Mío' FROM MAKES m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, 'Clio II' FROM MAKES m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, 'Clio Campus' FROM MAKES m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, 'Symbol' FROM MAKES m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, 'Sandero' FROM MAKES m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, 'Sandero Stepway' FROM MAKES m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, 'Logan' FROM MAKES m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, 'Kwid' FROM MAKES m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, 'Duster' FROM MAKES m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, 'Duster Oroch' FROM MAKES m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, 'Captur' FROM MAKES m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, 'Alaskan' FROM MAKES m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, 'Koleos' FROM MAKES m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, 'Fluence' FROM MAKES m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, 'Megane' FROM MAKES m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, 'Megane II' FROM MAKES m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, 'Megane III' FROM MAKES m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, 'Scenic' FROM MAKES m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, 'Grand Scenic' FROM MAKES m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, 'Laguna' FROM MAKES m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, 'Latitude' FROM MAKES m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, 'Talisman' FROM MAKES m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, 'Express' FROM MAKES m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, 'Kangoo' FROM MAKES m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, 'Kangoo Express' FROM MAKES m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, 'Kangoo Stepway' FROM MAKES m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, 'Master' FROM MAKES m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, 'Trafic' FROM MAKES m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, 'Twizy' FROM MAKES m WHERE m.name = 'Renault'
UNION ALL SELECT m.id, 'ZOE' FROM MAKES m WHERE m.name = 'Renault';

-- Script completo de marcas y modelos de autos del mercado argentino
-- PARTE 5: Marcas S-Z

-- TOYOTA
-- TOYOTA: Modelos históricos, actuales, variantes y utilitarios en Argentina
INSERT IGNORE INTO MAKES (name) VALUES ('Toyota');
INSERT IGNORE INTO MODELS (make_id, name)
SELECT m.id, 'Corolla' FROM MAKES m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Corolla XLi' FROM MAKES m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Corolla XEi' FROM MAKES m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Corolla SEG' FROM MAKES m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Corolla Cross' FROM MAKES m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Corolla Cross XLi' FROM MAKES m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Corolla Cross SEG Hybrid' FROM MAKES m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Yaris' FROM MAKES m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Yaris XS' FROM MAKES m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Yaris XLS' FROM MAKES m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Yaris S' FROM MAKES m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Etios' FROM MAKES m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Etios X' FROM MAKES m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Etios XLS' FROM MAKES m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Etios Cross' FROM MAKES m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Camry' FROM MAKES m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Camry XLE' FROM MAKES m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Camry Hybrid' FROM MAKES m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Prius' FROM MAKES m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Prius Hybrid' FROM MAKES m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Hilux' FROM MAKES m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Hilux DX' FROM MAKES m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Hilux SR' FROM MAKES m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Hilux SRV' FROM MAKES m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Hilux SRX' FROM MAKES m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Hilux Limited' FROM MAKES m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Hilux GR-S' FROM MAKES m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'SW4' FROM MAKES m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'SW4 SR' FROM MAKES m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'SW4 SRV' FROM MAKES m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'SW4 SRX' FROM MAKES m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'RAV4' FROM MAKES m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'RAV4 Hybrid' FROM MAKES m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Land Cruiser' FROM MAKES m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Land Cruiser Prado' FROM MAKES m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Land Cruiser 200' FROM MAKES m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, '4Runner' FROM MAKES m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, '4Runner SR5' FROM MAKES m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'C-HR' FROM MAKES m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'C-HR Hybrid' FROM MAKES m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Avanza' FROM MAKES m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Innova' FROM MAKES m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Hiace' FROM MAKES m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Hiace Commuter' FROM MAKES m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Commuter' FROM MAKES m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'FJ Cruiser' FROM MAKES m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Tercel' FROM MAKES m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Corona' FROM MAKES m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Crown' FROM MAKES m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Sprinter' FROM MAKES m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Celica' FROM MAKES m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'MR2' FROM MAKES m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Supra' FROM MAKES m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, '86' FROM MAKES m WHERE m.name = 'Toyota'
UNION ALL SELECT m.id, 'Yaris GR' FROM MAKES m WHERE m.name = 'Toyota';

-- VOLKSWAGEN
-- VOLKSWAGEN: Modelos históricos, actuales, variantes y utilitarios en Argentina
INSERT IGNORE INTO MAKES (name) VALUES ('Volkswagen');
INSERT IGNORE INTO MODELS (make_id, name)
SELECT m.id, 'Escarabajo' FROM MAKES m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Sedán' FROM MAKES m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Kombi' FROM MAKES m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Brasilia' FROM MAKES m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, '1500' FROM MAKES m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Gacel' FROM MAKES m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Senda' FROM MAKES m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Carat' FROM MAKES m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Gol' FROM MAKES m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Gol Power' FROM MAKES m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Gol Trend' FROM MAKES m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Gol Country' FROM MAKES m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Saveiro' FROM MAKES m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Saveiro Cross' FROM MAKES m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Voyage' FROM MAKES m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Fox' FROM MAKES m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Surán' FROM MAKES m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'CrossFox' FROM MAKES m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'SpaceFox' FROM MAKES m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Up!' FROM MAKES m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Polo' FROM MAKES m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Polo Classic' FROM MAKES m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Polo GTS' FROM MAKES m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Virtus' FROM MAKES m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Nivus' FROM MAKES m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'T-Cross' FROM MAKES m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Taos' FROM MAKES m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Tiguan' FROM MAKES m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Tiguan Allspace' FROM MAKES m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Touareg' FROM MAKES m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Amarok' FROM MAKES m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Amarok V6' FROM MAKES m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Caddy' FROM MAKES m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Transporter' FROM MAKES m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Multivan' FROM MAKES m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'California' FROM MAKES m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Passat' FROM MAKES m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Passat Variant' FROM MAKES m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Vento' FROM MAKES m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Vento GLI' FROM MAKES m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Jetta' FROM MAKES m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Golf' FROM MAKES m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Golf GTI' FROM MAKES m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Golf Variant' FROM MAKES m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Golf Country' FROM MAKES m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Bora' FROM MAKES m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Santana' FROM MAKES m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Pointer' FROM MAKES m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Sharan' FROM MAKES m WHERE m.name = 'Volkswagen'
UNION ALL SELECT m.id, 'Beetle' FROM MAKES m WHERE m.name = 'Volkswagen';

-- OTRAS MARCAS RELEVANTES

-- SUZUKI
INSERT IGNORE INTO MAKES (name) VALUES ('Suzuki');
INSERT IGNORE INTO MODELS (make_id, name)
SELECT m.id, 'Swift' FROM MAKES m WHERE m.name = 'Suzuki'
UNION ALL SELECT m.id, 'Baleno' FROM MAKES m WHERE m.name = 'Suzuki'
UNION ALL SELECT m.id, 'Vitara' FROM MAKES m WHERE m.name = 'Suzuki'
UNION ALL SELECT m.id, 'Jimny' FROM MAKES m WHERE m.name = 'Suzuki'
UNION ALL SELECT m.id, 'S-Cross' FROM MAKES m WHERE m.name = 'Suzuki'
UNION ALL SELECT m.id, 'Grand Vitara' FROM MAKES m WHERE m.name = 'Suzuki'
UNION ALL SELECT m.id, 'Fun' FROM MAKES m WHERE m.name = 'Suzuki'
UNION ALL SELECT m.id, 'APV' FROM MAKES m WHERE m.name = 'Suzuki';

-- CHERY
INSERT IGNORE INTO MAKES (name) VALUES ('Chery');
INSERT IGNORE INTO MODELS (make_id, name)
SELECT m.id, 'QQ' FROM MAKES m WHERE m.name = 'Chery'
UNION ALL SELECT m.id, 'Tiggo' FROM MAKES m WHERE m.name = 'Chery'
UNION ALL SELECT m.id, 'Tiggo 2' FROM MAKES m WHERE m.name = 'Chery'
UNION ALL SELECT m.id, 'Tiggo 3' FROM MAKES m WHERE m.name = 'Chery'
UNION ALL SELECT m.id, 'Tiggo 4' FROM MAKES m WHERE m.name = 'Chery'
UNION ALL SELECT m.id, 'Tiggo 5' FROM MAKES m WHERE m.name = 'Chery'
UNION ALL SELECT m.id, 'Tiggo 7' FROM MAKES m WHERE m.name = 'Chery'
UNION ALL SELECT m.id, 'Tiggo 8' FROM MAKES m WHERE m.name = 'Chery'
UNION ALL SELECT m.id, 'Arrizo 5' FROM MAKES m WHERE m.name = 'Chery'
UNION ALL SELECT m.id, 'Arrizo 7' FROM MAKES m WHERE m.name = 'Chery';

-- GEELY
INSERT IGNORE INTO MAKES (name) VALUES ('Geely');
INSERT IGNORE INTO MODELS (make_id, name)
SELECT m.id, 'Emgrand' FROM MAKES m WHERE m.name = 'Geely'
UNION ALL SELECT m.id, 'Emgrand GS' FROM MAKES m WHERE m.name = 'Geely'
UNION ALL SELECT m.id, 'Emgrand X7' FROM MAKES m WHERE m.name = 'Geely'
UNION ALL SELECT m.id, 'Coolray' FROM MAKES m WHERE m.name = 'Geely'
UNION ALL SELECT m.id, 'Okavango' FROM MAKES m WHERE m.name = 'Geely';

-- HAVAL
INSERT IGNORE INTO MAKES (name) VALUES ('Haval');
INSERT IGNORE INTO MODELS (make_id, name)
SELECT m.id, 'H1' FROM MAKES m WHERE m.name = 'Haval'
UNION ALL SELECT m.id, 'H2' FROM MAKES m WHERE m.name = 'Haval'
UNION ALL SELECT m.id, 'H6' FROM MAKES m WHERE m.name = 'Haval'
UNION ALL SELECT m.id, 'H9' FROM MAKES m WHERE m.name = 'Haval';

-- JAC
INSERT IGNORE INTO MAKES (name) VALUES ('JAC');
INSERT IGNORE INTO MODELS (make_id, name)
SELECT m.id, 'S2' FROM MAKES m WHERE m.name = 'JAC'
UNION ALL SELECT m.id, 'S3' FROM MAKES m WHERE m.name = 'JAC'
UNION ALL SELECT m.id, 'S5' FROM MAKES m WHERE m.name = 'JAC'
UNION ALL SELECT m.id, 'T6' FROM MAKES m WHERE m.name = 'JAC'
UNION ALL SELECT m.id, 'T8' FROM MAKES m WHERE m.name = 'JAC';

-- BAIC
INSERT IGNORE INTO MAKES (name) VALUES ('BAIC');
INSERT IGNORE INTO MODELS (make_id, name)
SELECT m.id, 'X25' FROM MAKES m WHERE m.name = 'BAIC'
UNION ALL SELECT m.id, 'X35' FROM MAKES m WHERE m.name = 'BAIC'
UNION ALL SELECT m.id, 'X55' FROM MAKES m WHERE m.name = 'BAIC'
UNION ALL SELECT m.id, 'X65' FROM MAKES m WHERE m.name = 'BAIC';

-- DFSK
INSERT IGNORE INTO MAKES (name) VALUES ('DFSK');
INSERT IGNORE INTO MODELS (make_id, name)
SELECT m.id, 'Glory 500' FROM MAKES m WHERE m.name = 'DFSK'
UNION ALL SELECT m.id, 'Glory 560' FROM MAKES m WHERE m.name = 'DFSK'
UNION ALL SELECT m.id, 'Glory 580' FROM MAKES m WHERE m.name = 'DFSK'
UNION ALL SELECT m.id, 'C31' FROM MAKES m WHERE m.name = 'DFSK'
UNION ALL SELECT m.id, 'C32' FROM MAKES m WHERE m.name = 'DFSK'
UNION ALL SELECT m.id, 'C35' FROM MAKES m WHERE m.name = 'DFSK'
UNION ALL SELECT m.id, 'K01' FROM MAKES m WHERE m.name = 'DFSK'
UNION ALL SELECT m.id, 'K02' FROM MAKES m WHERE m.name = 'DFSK'
UNION ALL SELECT m.id, 'K05' FROM MAKES m WHERE m.name = 'DFSK'
UNION ALL SELECT m.id, 'K07' FROM MAKES m WHERE m.name = 'DFSK';
